# Normally run from the folder outside the repo.
version: '3.4'
services:
  mongodb:
    image: mongo:3.4
    volumes:
     - ./mongo:/data/db

  mongoadmin:  # web UI for mongo
    image: mongo-express
    ports:
     - "8081:8081"
    links:
     - mongodb:mongo
    environment:
     - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
     - ME_CONFIG_BASICAUTH_USERNAME=admin
     - ME_CONFIG_BASICAUTH_PASSWORD=test
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    links:
      - "mongodb"
    environment:
      - NODE_ENV=production
    command: bash entrypoint.production.sh
    ports:
      - "3000:3000"
