version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./singularIT:/usr/src/app/
    environment:
      - NODE_ENV=development
    command: bash entrypoint.development.sh

