# Normally run from the folder outside the repo.
version: '2.0'
services:
  mongodb:
    image: mongo:3.4
    volumes:
     - ./mongo:/data/db

  mongoadmin:  # web UI for mongo
    image: mongo-express
    ports:
     - "8081:8081"
    links:
     - mongodb:mongo
    environment:
     - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
     - ME_CONFIG_BASICAUTH_USERNAME=admin
     - ME_CONFIG_BASICAUTH_PASSWORD=test
  app:
    image: snic/disruptit:0.0.1
    volumes:
      - ./disruptIT:/usr/src/app
    links:
      - "mongodb"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]
    ports:
      - "3000:3000"
  # nginx:
  #   image: nginx:1.13.5
  #   network_mode: "host"
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - "/root/disruptIT/Dockerfile/nginx.conf:/etc/nginx/nginx.conf"
  #     - "/etc/letsencrypt/archive/disrupt-it.nl:/etc/letsencrypt/live/disrupt-it.nl"